-- MySQL Script generated by MySQL Workbench
-- sáb 05 dez 2020 14:51:20
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bd_pizzaria
-- -----------------------------------------------------
-- Criada por Salomão Francisco da Silva 62 99447-4551

-- -----------------------------------------------------
-- Schema bd_pizzaria
--
-- Criada por Salomão Francisco da Silva 62 99447-4551
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_pizzaria` DEFAULT CHARACTER SET utf8 ;
USE `bd_pizzaria` ;

-- -----------------------------------------------------
-- Table `bd_pizzaria`.`tb_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_pizzaria`.`tb_cliente` (
  `id` INT NOT NULL,
  `cpf` VARCHAR(20) NULL,
  `nome` VARCHAR(256) NULL,
  `telefone` VARCHAR(20) NULL,
  `endereco` VARCHAR(256) NULL,
  `cidade` VARCHAR(128) NULL,
  `uf` VARCHAR(2) NULL,
  `cep` VARCHAR(20) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_pizzaria`.`tb_funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_pizzaria`.`tb_funcionario` (
  `id` INT NOT NULL,
  `cpf` VARCHAR(20) NULL,
  `nome` VARCHAR(256) NULL,
  `telefone` VARCHAR(20) NULL,
  `data_admissao` VARCHAR(10) NULL,
  `endereco` VARCHAR(256) NULL,
  `cidade` VARCHAR(128) NULL,
  `uf` VARCHAR(2) NULL,
  `cep` VARCHAR(20) NULL,
  `cargo` VARCHAR(300) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_pizzaria`.`tb_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_pizzaria`.`tb_produto` (
  `id` INT NOT NULL,
  `codigo` VARCHAR(16) NULL,
  `nome` VARCHAR(256) NULL,
  `preco` VARCHAR(16) NULL,
  `caracteristicas` VARCHAR(300) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_pizzaria`.`tb_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_pizzaria`.`tb_pedido` (
  `id` INT NOT NULL,
  `cliente_nome` VARCHAR(256) NULL,
  `cliente_cpf` VARCHAR(20) NOT NULL,
  `cliente_telefone` VARCHAR(20) NULL,
  `cliente_endereco` VARCHAR(256) NULL,
  `lista_produtos` TEXT(1000) NOT NULL,
  `total` VARCHAR(10) NULL,
  `pagamento_realizado` VARCHAR(3) NULL,
  `entrega` VARCHAR(3) NULL,
  `comanda` VARCHAR(3) NULL,
  `comanda_mesa` VARCHAR(128) NULL,
  `comanda_funcionario` VARCHAR(256) NOT NULL,
  `data` VARCHAR(12) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_pedido_tb_cliente_idx` (`cliente_cpf` ASC) VISIBLE,
  INDEX `fk_tb_pedido_tb_funcionario1_idx` (`comanda_funcionario` ASC) VISIBLE,
  INDEX `fk_tb_pedido_tb_produto1_idx` (`lista_produtos` ASC) VISIBLE,
  CONSTRAINT `fk_tb_pedido_tb_cliente`
    FOREIGN KEY (`cliente_cpf`)
    REFERENCES `bd_pizzaria`.`tb_cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_pedido_tb_funcionario1`
    FOREIGN KEY (`comanda_funcionario`)
    REFERENCES `bd_pizzaria`.`tb_funcionario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_pedido_tb_produto1`
    FOREIGN KEY (`lista_produtos`)
    REFERENCES `bd_pizzaria`.`tb_produto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
